logging:
  level:
    root: info
    web: debug
#    sql: debug
spring:
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/auth_server
    username: auth_server
    password: auth_server
