logging:
  level:
    root: info
    web: debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
#    sql: debug
spring:
  devtools:
    livereload:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/auth_server
    username: auth_server
    password: auth_server
auth:
  key-path: key/auth-server.jks
  key-password: auth-server-pass
  alias: auth-server
  store-password: auth-server-pass
